 /**: 
  global_costmap:
    global_costmap:
      ros__parameters:
        footprint: "[[1.485, 0.4], [1.485, -0.4], [-0.35, -0.4], [-0.35, 0.4]]"
        inflation_layer:
          cost_scaling_factor: 8.0
          inflation_radius: 1.2
      
        stvl_layer:
          voxel_decay: 5.
          mark_threshold: 2

  
  local_costmap:
    local_costmap:
        footprint: "[[1.485, 0.4], [1.485, -0.4], [-0.35, -0.4], [-0.35, 0.4]]"



  controller_server:
    ros__parameters:
      
      # Remark: Yaml Anchors and aliases are not supported by rcl https://github.com/ros2/rcl/issues/563. We use pyYaml in get_config to workaround
      GeneralFollowPath: &GeneralFollowPath
        publish_feedback: False
        plugin: "teb_local_planner::TebLocalPlannerROS"
        dt_ref: 0.3
        dt_hysteresis: 0.1
        global_plan_overwrite_orientation: False
        feasibility_check_no_poses: 22
        global_plan_viapoint_sep: 0.4
        allow_init_with_backwards_motion: True
        max_global_plan_lookahead_dist: 4.0

        # Custom added parameters
        feasibility_check_stop_poses: 15
        feasibility_check: True
        feasibility_check_lookahead_distance: 2.7

        # Robot
        footprint_model:
          type: "line"
          line_end: [1.6, 0.0]
          line_start: [0.1, 0.0]
        max_vel_x: 0.7
        max_vel_x_backwards: 0.5
        max_vel_theta: 0.4
        acc_lim_x: 0.4
        acc_lim_theta: 0.4
        use_proportional_saturation: True
        min_turning_radius: 0.3

        # Obstacles
        min_obstacle_dist: 0.45
        inflation_dist: 1.0
        obstacle_poses_affected: 20

        include_dynamic_obstacles: False
        include_costmap_obstacles: False
        costmap_converter_plugin: ""
        costmap_converter_spin_thread: False
        costmap_converter_rate: 1

        obstacle_association_force_inclusion_factor: 1.0
        costmap_obstacles_behind_robot_dist: 1.0
        obstacle_proximity_ratio_max_vel: 1.0
        obstacle_proximity_lower_bound: 0.0
        obstacle_proximity_upper_bound: 1.0

        # Trajectory
        control_look_ahead_poses: 4

        # Optimization

        weight_inflation: 0.3
        optimization_verbose: False
        weight_viapoint: 0.3
        no_inner_iterations: 5
        no_outer_iterations: 4
        weight_velocity_obstacle_ratio: 0.0
        weight_obstacle: 50.0
        weight_kinematics_forward_drive: 0.3

        # Homotopy Class Planner
        enable_homotopy_class_planning: True
        enable_multithreading: True
        max_number_classes: 3

        # GoalTolerance
        free_goal_vel: true
        
      LaneFollowPath:
        # Obstacles
        min_obstacle_dist: 0.5