 /**: 
  global_costmap:
    global_costmap:
      ros__parameters:
        footprint: "[[1.485, 0.4], [1.485, -0.4], [-0.35, -0.4], [-0.35, 0.4]]"
        inflation_layer:
          cost_scaling_factor: 8.0
          inflation_radius: 1.2
      
        stvl_layer:
          voxel_decay: 5.
          mark_threshold: 2

  
  local_costmap:
    local_costmap:
      ros__parameters:
        footprint: "[[1.485, 0.4], [1.485, -0.4], [-0.35, -0.4], [-0.35, 0.4]]"


  controller_server:
    ros__parameters:
      general_goal_checker:
        xy_goal_tolerance: 1.1
        yaw_goal_tolerance: 1.2

      # lower tolerance for reaching the final goal
      exact_path_goal_checker:
        xy_goal_tolerance: 0.2
        yaw_goal_tolerance: 0.06
      
      # Remark: Yaml Anchors and aliases are not supported by rcl https://github.com/ros2/rcl/issues/563. We use pyYaml in get_config to workaround
      GeneralFollowPath: &GeneralFollowPath
        # Obstacles
        min_obstacle_dist: 0.55
        inflation_dist: 1.2
        weight_viapoint: 0.1
        
      LaneFollowPath:
        # Obstacles
        min_obstacle_dist: 0.55

      ExactGoalReachFollowPath:
        max_global_plan_lookahead_dist: 4.0
