/**:
  pallet_transportation_action_servers:
    ros__parameters:
      side_offset: 0.4
      consider_fillgrade: true
      approach_goal_distance_meters: 1.5
      platform_approach_goal_offset: 0.4
      platform_marker_size: 0.11
      markers_to_w2mo_bin_distance: 0.6 # Positive if bin is behind markers (pre-approach goal adjustment)
      goal_offset_x: -1.5 # Markers to goal  ## Negative is deeper in the bin ### if changed also change pallet_putdown_to_platform.xml line 58
      goal_offset_y: 0.0 # Positive is to the right, when looking from AMR towards platform
      angular_goal_adjustment: 0.0 # Positive is counterclockwise
      lift_height_for_pickup: 0.11 # Fork lift level change to lift the pallet ## 14->18cm for the basement
      lift_height_for_driving_out: 0.21 # We lift the forks a bit higher when driving out of the platform

  assign_bin_to_amr_action_server:
    ros__parameters:
      bin_locking_distance_meters: 8.0 # distance when bin is reserved for sole use by this AMR. Designed to prevent issues when e.g. 2 AMRs try to put a pallet to the same bin
      bin_unlocking_distance_meters: 3.0 # distance when bin is made available for other AMRs

  vehicles_intersection_action_servers:
    ros__parameters:
      reduce_speed_plan_occupied_by_amr:
        no_reduce.distance: 9.0
        no_reduce.speed: 1.0
        max_reduce.distance: 3.0
        max_reduce.speed: 0.0

      reduce_speed_amr_near_plan:
        no_reduce.distance: 8.0
        no_reduce.speed: 1.0
        max_reduce.distance: 2.0
        max_reduce.speed: 0.0

      reduce_speed_plan_occupied_by_forklift:
        no_reduce.distance: 10.0
        no_reduce.speed: 1.0
        max_reduce.distance: 3.0
        max_reduce.speed: 0.0

      reduce_speed_forklift_near_plan:
        no_reduce.distance: 7.0
        no_reduce.speed: 1.0
        max_reduce.distance: 0.5
        max_reduce.speed: 0.0

      reduce_speed_plan_occupied_by_amr_in_waiting_area:
        no_reduce.distance: 6.0
        no_reduce.speed: 1.0
        max_reduce.distance: 1.0
        max_reduce.speed: 0.0
  
  path_finding_action_servers:
    ros__parameters:
      distance_skip_following_w2mo_paths: 3.0 # the minimum limit for the build of a path with w2mo paths
      threshold_distance_of_cut_off_start: 1.5 # threshold value of the distance between goal and following w2mo paths
      threshold_distance_of_cut_off_end: 4.0 # threshold value of the distance between goal and following w2mo paths
      max_distance_to_w2mo_path: 6.0 # follow w2mo path when this close to it
      max_path_planning_length: 23.0 # max path planning length in ComputePathAlongWaypoints node
